<!--Projects Homepage-->
<?php
include_once UTILITY.'class.util.inc';
include_once MODULES_PROJECT.'dao/class.projectdao.inc';
include_once MODULES_PROJECT.'dao/class.projectHomedao.inc';

class ProjectHomeBao{

    private $_ProjectHomeDao;

    public function __construct()
    {
        $this->_ProjectHomeDao=new ProjectHomeDao();
    }

    //get paginated projects
    public function getLimitProject($page,$limit){
        $Result=$this->_ProjectHomeDao->getLimitProject($page,$limit);

        if(!$Result->getIsSuccess()){
            $Result->setResultObject("Database failure in ProjectHomeDao.getLimitProject($page,$limit)");
        }

        return $Result;
    }
}
?>
