<!--Search specific thesis-->
<?php
include_once UTILITY.'class.util.inc';
include_once MODULES_THESIS.'dao/class.searchThesisdao.inc';

/*
	User Business Object
*/
Class SearchThesisBao
{

    private $_SearchThesisDao;

    public function __construct()
    {
        $this->_SearchThesisDao=new SearchThesisDao();
    }   

    //get searched thesis
    public function getSearchedThesis(){
        $Result=$this->_SearchThesisDao->getSearchedThesis();

        if(!$Result->getIsSuccess()){
            $Result->setResultObject("Database failure in SearchThesisDao.getSearchedThesis()");
        }
        return $Result;
    }
    
    //get all students
    public function getAllStudents(){
        $Result=$this->_SearchThesisDao->getAllStudents();
        
        if(!$Result->getIsSuccess()){
            $Result->setResultObject("Database failure in SearchThesisDao.getAllStudents()");
        }
        return $Result;
    }   
    
}
?>
